### ISSUE TITLE
Intégration de la page des installations

### ISSUE THREAD

**Issue by mineraux** [mineraux/make-bench-great-again#64]
- [x] Ajouter le blur au scroll
- [x] Ajouter l'illustation
- [ ] Ajouter les témoignages
- [x] Ajouter le push vers Twitter
- [ ] Ajouter le tuto
- [ ] Ajouter les tweet d'une installation

**Comment by AlexandreMasse** [comment]
Nouvelle issue pour la page installation --> #162
